### ISSUE TITLE
Example documentation 

### ISSUE THREAD

**Issue by njoeres** [DLR-AE/CampbellViewer#52]
Add information on which versions we used (Bladed, HAWCStab) for the examples. (with/without aero states, different turbine setups, different tool versions, etc.)

**Comment by hendrikverdonck** [comment]
I added a short description for the example and I also added a new section 'tool specific information'. I added there a bit more information on the Bladed interface.

**Comment by njoeres** [comment]
I think it's okay how it is and we can merge the branches. So I will close this issue.
